In [18]:
reload("TruncatedNormal")

In [4]:
a = (100, 200); b = (120, 230); 
μ = (0,0); Σ = [1 0.9; 0.9 1];
@show TruncatedNormal.gauss2Dmoment1(μ,Σ,a,b);
@show TruncatedNormal.gauss2Dmoment2(μ,Σ,a,b);
@show TruncatedNormal.gauss2Dmoment11(μ,Σ,a,b);
@show TruncatedNormal.gauss2Dmoment22(μ,Σ,a,b);
@show TruncatedNormal.gauss2Dmoment12(μ,Σ,a,b);

TruncatedNormal.gauss2Dmoment1(μ, Σ, a, b) = 119.99683376555747
TruncatedNormal.gauss2Dmoment2(μ, Σ, a, b) = 200.0020650607263
TruncatedNormal.gauss2Dmoment11(μ, Σ, a, b) = 14399.240123782782
TruncatedNormal.gauss2Dmoment22(μ, Σ, a, b) = 40000.82603281923
TruncatedNormal.gauss2Dmoment12(μ, Σ, a, b) = 23999.614553860327


In [19]:
lb = [724.1281846948646, -0.3248194681994417];
ub = [2518.3641949975517, 0.5111929404723518];
Σ = [1. -0.022020238658485524; -0.022020238658485524 1.];
N = 1000000
X = TruncatedNormal.R.sample_truncated_bivariate_gaussian(lb, ub, Σ, N);

In [20]:
mean(X, 2)

2×1 Array{Float64,2}:
 724.13    
  -0.261458

In [17]:
mean(X[2,:] .* X[2,:])

0.07230821927819264

In [9]:
lb = [0,0]
ub = [1,1]
Sig = [1 0; 0 1]
N = 10
RCall.@rlibrary("TruncatedNormal")
RCall.@rput lb
RCall.@rput ub
RCall.@rput Sig
RCall.@rput N
RCall.R"X <- TruncatedNormal::mvrandn(l = lb, u = ub, Sig = Sig, n = N)"
RCall.@rget X

2×10 Array{Float64,2}:
 0.26167   0.78241   0.24387   0.362134  …  0.664261  0.885704  0.874943
 0.164832  0.510643  0.411596  0.132475     0.496726  0.852293  0.609718

In [10]:
X

2×10 Array{Float64,2}:
 0.26167   0.78241   0.24387   0.362134  …  0.664261  0.885704  0.874943
 0.164832  0.510643  0.411596  0.132475     0.496726  0.852293  0.609718